DevCard_MVC/Models/Article.cs
namespace DevCard_MVC.Models
{
    public class Article
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }

        public Article(long id, string title, string image, string description)
        {
            Id = id;
            Title = title;
            Image = image;
            Description = description;
        }
    }
}

DevCard_MVC/Models/ContactForm.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DevCard_MVC.Models
{
    public class ContactForm
    {
        [Required(ErrorMessage = "این فیلد اجباری است")]
        [MinLength(3,ErrorMessage = "حداقل طول نام ، 3 کاراکتر است")]
        [MaxLength(100, ErrorMessage = "طول نام ، بیش از حد مجاز است")]
        public string name { get; set; }

        [Required(ErrorMessage = "این فیلد اجباری است")]
        [EmailAddress(ErrorMessage = "عبارت وارد شده ایمیل صحیحی نیست")]
        public string email { get; set; }

        [Required(ErrorMessage = "این فیلد اجباری است")]
        public string message { get; set; }

        public int services { get; set; }

        public SelectList Services { get; set; }
    }
}

DevCard_MVC/Models/ErrorViewModel.cs
using System;

namespace DevCard_MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DevCard_MVC/Models/Project.cs
namespace DevCard_MVC.Models
{
    public class Project
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Client { get; set; }
        public string Url { get; set; }

		public Project(long id, string name, string description,string image, string client,string url)
		{
			Id = id;
			Name = name;
			Description = description;
			Image = image;
			Client = client;
			Url = url;
		}
	}
}

DevCard_MVC/Models/Service.cs
namespace DevCard_MVC.Models
{
    public class Service
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Service(int id, string name)
        {
            Id = id;
            Name = name;
        }
    }
}

DevCard_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using DevCard_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DevCard_MVC.Controllers
{
    //[Route("/inventory/products")]
    //localhost:5001/inventory/products/index
    //localhost:5001/inventory/products/contact
    public class HomeController : Controller
    {
        private readonly List<Service> _services = new List<Service>
        {
            new Service(1,"نقره ای"),
            new Service(2,"طلایی"),
            new Service(3,"پلاتین"),
            new Service(4,"الماس"),
        };

        //localhost:5001/inventory/products/MyIndex
        //[Route("MyIndex/{name?}/{model?}")]
        public IActionResult Index(string name,string model)
        {
            return View();
        }

        public IActionResult ProjectDetails(long id)
        {
            var project = ProjectStore.GetProjectBy(id);
            return View(project);
        }

        //localhost:5001/inventory/products/ContactPage
        //[HttpGet("ContactPage")]
        //[Route("ContactPage")]
        [HttpGet]
        public IActionResult Contact()
        {
            var model = new ContactForm()
            {
                Services = new SelectList(_services, "Id", "Name")
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Contact(ContactForm model)
        {
            model.Services = new SelectList(_services, "Id", "Name");
            //if (ModelState.IsValid == false)
            if (!ModelState.IsValid)
            {
                ViewBag.error = "اطلاعات وارد شده صحیح نیست ، لطفا دوباره تلاش کنید";
                return View(model);
            }
            
            ModelState.Clear();

            model = new ContactForm
            {
                Services = new SelectList(_services, "Id", "Name")
            };
            ViewBag.success = "پیغام شما با موفقیت ارسال شد ، باتشکر از شما";
            return View(model);
            //return RedirectToAction("Index");
        }

        //[HttpPost]
        //public JsonResult Contact(ContactForm form)
        //{
        //    Console.WriteLine(form.ToString());
        //    return Json(Ok());
        //}

        //[HttpPost]
        //public JsonResult Contact(IFormCollection form)
        //{
        //    var name = form["name"];
        //    return Json(Ok());
        //}


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevCard_MVC/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;

namespace DevCard_MVC.Controllers
{
    public class TestController : Controller
    {
        //public IActionResult Index()
        //{
        //    return PartialView("Footer");
        //}

        //public PartialViewResult Index()
        //{
        //    return PartialView("Footer");
        //}

        //public ContentResult Index()
        //{
        //    //return Content("<h1>hello Asp.net Core MVC Student");
        //    return Content($"<h1>hello Asp.net Core MVC Student</h1><script>confirm('این سوال من است؟');</script>",
        //        "text/html");
        //}

        //public EmptyResult Index()
        //{
        //    //return null;
        //    return new EmptyResult();
        //}

        //public FileResult Index()
        //{
        //    //return File("~/test.txt", "text/html");
        //    var fileByte = System.IO.File.ReadAllBytes("wwwroot/test.txt");
        //    const string fileName = "testFile.txt";
        //    return File(fileByte, MediaTypeNames.Text.Plain, fileName);
        //}

        //public JsonResult Index()
        //{
        //    return Json(new
        //    {
        //        id = 12,
        //        name = "hossein",
        //        job = "programmer",
        //        site = "atriya.com"
        //    });
        //}

        //public JavascriptResult Index()
        //{
        //    return new JavascriptResult("alert('salam salam hamegi salam!!!')");
        //}

        //public RedirectResult Index()
        //{
        //    return Redirect("http://www.atriya.com");
        //}

        //public RedirectToActionResult Index()
        //{
        //    return RedirectToAction("Contact", "Home");
        //}

        public IActionResult Index()
        {
            //return new OkResult();
            //return new NotFoundResult();
            //return new BadRequestResult();
            //return new NoContentResult();
            return new StatusCodeResult(401);
        }
    }

    //public class JavascriptResult : ContentResult
    //{
    //    public JavascriptResult(string data)
    //    {
    //        Content = data;
    //        ContentType = "application/javascript";
    //    }
    //}
}

DevCard_MVC/ViewComponents/LatestArticlesViewComponent.cs
using System.Collections.Generic;
using DevCard_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_MVC.ViewComponents
{
    public class LatestArticlesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var articles = new List<Article>
            {
                new Article(1,"آموزش Asp.net.core","blog-post-thumb-card-5.jpg","کاملترین پکیج آموزش asp.net"),
                new Article(2,"آموزش GitHub","blog-post-thumb-card-1.jpg","کاملترین پکیج آموزش Git"),
                new Article(3,"آموزش Onion Architecture","blog-post-thumb-card-3.jpg","کاملترین پکیج آموزش Onion Architecture"),
                new Article(4,"آموزش طراحی سایت","blog-post-thumb-card-4.jpg","کاملترین پکیج آموزش طراحی سایت")
            };
            return View("_LatestArticles",articles);
        }
    }
}

DevCard_MVC/ViewComponents/ProjectsViewComponent.cs
using DevCard_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace DevCard_MVC.ViewComponents
{
	public class ProjectsViewComponent : ViewComponent
	{
        public IViewComponentResult Invoke()
        {
            var projects = ProjectStore.GetProjects();

            return View("_Projects",projects);
        }
	}
}

DevCard_MVC/Views/Home/Components/LatestArticles/_LatestArticles.cshtml
@model List<Article>

<section class="latest-blog-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
		<div class="row">

			@foreach (var article in Model)
			{
				<div class="col-md-4 mb-5">
					<div class="card blog-post-card">
						<img class="card-img-top" src="~/assets/images/blog/@article.Image" alt="@article.Title" title="@article.Description">
						<div class="card-body">
							<h5 class="card-title">
								<a class="theme-link" href="#">
									@article.Title
								</a>
							</h5>
							<p class="card-text">
								@article.Description
							</p>
							<p class="mb-0"><a class="more-link" href="#">ادامه مطلب</a></p>

						</div>
					</div>
				</div>
			}

		</div>
	</div>
</section>

DevCard_MVC/Views/Home/Components/Projects/_Projects.cshtml
@model IEnumerable<DevCard_MVC.Models.Project>

<section class="featured-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5" id="projects">پروژه ها</h2>
		<div class="row">
			@foreach (var project in Model)
			{
				<div class="col-md-6 mb-5">
					<div class="card project-card">
						<div class="row no-gutters">
							<div class="col-lg-4 card-img-holder">
								<img src="assets/images/project/@project.Image" class="card-img" alt="@project.Image" title="@project.Description">
							</div>
							<div class="col-lg-8">
								<div class="card-body">
									<h5 class="card-title">
										<a asp-controller="Home" asp-action="ProjectDetails" asp-route-id="@project.Id" class="theme-link">
											@project.Id : @project.Name
										</a>
									</h5>
									<p class="card-text">
										@project.Description
									</p>
									<p class="card-text"><small class="text-muted">مشتری: @project.Client</small></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			}


		</div>
	</div>
</section>

DevCard_MVC/Views/Home/Contact.cshtml
@model ContactForm
@{
	ViewData["Title"] = "Contact With Me";
}


<section class="cta-section theme-bg-light py-5">
	<div class="container text-center single-col-max-width">
		<h2 class="heading">ارتباط با من</h2>
		<div class="intro">
			<p>
				شما می توانید از طریق فرم زیر با من ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
				نوشته و ارسال کنید.
			</p>
			<p>از طریق شبکه های اجتماعی با من در ارتباط باشید</p>
			<ul class="list-inline mb-0">
				<li class="list-inline-item mb-3">
					<a class="twitter" href="#">
						<i class="fab fa-twitter fa-fw fa-lg"></i>
					</a>
				</li>

				<li class="list-inline-item mb-3">
					<a class="linkedin" href="#">
						<i class="fab fa-linkedin-in fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="github" href="#">
						<i class="fab fa-github-alt fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="instagram" href="https://instagram.com/hafez._.007">
						<i class="fab fa-instagram fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="telegram" href="#">
						<i class="fab fa-twitter fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="medium" href="#">
						<i class="fab fa-medium-m fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="codepen" href="#">
						<i class="fab fa-codepen fa-fw fa-lg"></i>
					</a>
				</li>
			</ul>
		</div>
	</div>
</section>
<section class="contact-section px-3 py-5 p-md-5">
	<div class="container">
		
		@if (!string.IsNullOrWhiteSpace(ViewBag.success))
		{
			<div class="alert-success">
				<p>@ViewBag.success</p>
			</div>
		}

		@if (!string.IsNullOrWhiteSpace(ViewBag.error))
		{
			<div class="alert-danger">
				<p>@ViewBag.error</p>
			</div>
		}

		<form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact">
			<h3 class="text-center mb-3">در دسترس باشید!</h3>
			<div class="form-row">
				<div class="form-group col-md-6">
					<label class="sr-only" asp-for="name">نام</label>
					<input type="text" class="form-control" asp-for="name" placeholder="نام">
					<span asp-validation-for="name" class="text-danger"></span>
				</div>
				<div class="form-group col-md-6">
					<label class="sr-only" asp-for="email">ایمیل</label>
					<input type="email" class="form-control" asp-for="email" placeholder="ایمیل">
					<span asp-validation-for="email" class="text-danger"></span>
				</div>
				<div class="form-group col-12">
					<select class="custom-select" asp-for="services" asp-items="Model.Services">
						<option value="0" selected="selected">سرویس مورد نظر خود را انتخاب کنید...</option>
						
					</select>
				</div>
				<div class="form-group col-12">
					<label class="sr-only" asp-for="message">پیغام شما</label>
					<textarea class="form-control" asp-for="message"
							  placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
					<span asp-validation-for="message" class="text-danger"></span>
				</div>
				<div class="form-group col-12">
					<button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
				</div>
			</div>
		</form>
	</div>
</section>

DevCard_MVC/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Hafez Cheraghi";
}

<section class="about-me-section p-3 p-lg-5 theme-bg-light">
	<div class="container">
		<div class="profile-teaser media flex-column flex-lg-row">
			<img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="assets/images/Hafez.jpg" alt="">
			<div class="media-body">
				<h2 class="name font-weight-bold mb-1">حافظ چراغی</h2>
				<div class="tagline mb-3">برنامه نویس</div>
				<div class="bio mb-4">
					.سلام حافظ چراغی هستم ، متولد 1382 ساکن کرمانشاه و علاقمند به برنامه نویسی هستم
				</div>
				<div class="mb-4">
					<a class="btn btn-primary mr-2 mb-3" href="http://www.instagram.com/hafez._.007">
						<i class="fas fa-arrow-alt-circle-right ml-2"></i><span class="d-none d-md-inline">
							اینستاگرام من
						</span> 
					</a>
					<a class="btn btn-secondary mb-3" href="#projects">
						<i class="fas fa-file-alt ml-2"></i>
						<span class="d-none d-md-inline">مشاهده </span> نمونه کارها
					</a>
				</div>
			</div>

		</div>
	</div>
</section>

@*Loading Partial View*@

@*<partial name="Projects"/>
*@
@*@await Html.PartialAsync("Projects",new List<Project>())*@
@*@await Html.PartialAsync("Projects")*@

@*//End Loading Partial View*@

@*Loading View Component*@

@await Component.InvokeAsync("Projects")

<div class="container">
	<hr>
</div>

@await Component.InvokeAsync("LatestArticles")

@*//End Loading View Component*@

DevCard_MVC/Views/Home/ProjectDetails.cshtml
@model Project
@{
	ViewData["Title"] = "جزئیات پروژه";
}
<section class="cta-section theme-bg-light py-5">
	<div class="container text-center single-col-max-width">
		<div class="intro">
			<p>
				شما می توانید از طریق فرم زیر با من ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
				نوشته و ارسال کنید.
			</p>
			<p>از طریق شبکه های اجتماعی با من در ارتباط باشید</p>
			<ul class="list-inline mb-0">
				<li class="list-inline-item mb-3">
					<a class="twitter" href="#">
						<i class="fab fa-twitter fa-fw fa-lg"></i>
					</a>
				</li>

				<li class="list-inline-item mb-3">
					<a class="linkedin" href="#">
						<i class="fab fa-linkedin-in fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="github" href="#">
						<i class="fab fa-github-alt fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="instagram" href="https://instagram.com/hafez._.007">
						<i class="fab fa-instagram fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="telegram" href="#">
						<i class="fab fa-twitter fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="medium" href="#">
						<i class="fab fa-medium-m fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="codepen" href="#">
						<i class="fab fa-codepen fa-fw fa-lg"></i>
					</a>
				</li>
			</ul>
		</div>
	</div>
</section>
<section class="contact-section px-3 py-5 p-md-5">
	<div class="container">
		<table class="table table-bordered table-hover">

			<thead>
				<tr>
					<td>Id</td>
					<td>Image</td>
					<td>Name</td>
					<td>Description</td>
					<td>Client</td>
				</tr>
			</thead>

			<tbody>
				<tr>
					<td>@Model.Id</td>
					<td><img src="~/assets/images/project/@Model.Image" width="100px" /></td>
					<td>@Model.Name</td>
					<td>@Model.Description</td>
					<td>@Model.Client</td>
				</tr>
			</tbody>

		</table>
	</div>
</section>

DevCard_MVC/Views/Shared/Footer.cshtml
<footer class="footer text-center py-4">
	<small class="copyright">تولید شده توسط &copy; <a href="http://www.instagram.com/hafez._.007" target="_blank">حافظ چراغی</a></small>
</footer>

DevCard_MVC/Views/Shared/Header.cshtml
<header class="header text-center">
	<div class="force-overflow">
		<h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">حافظ چراغی</a></h1>

		<nav class="navbar navbar-expand-lg navbar-dark">

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
			        aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column">
				<div class="profile-section pt-3 pt-lg-0">
					<img class="profile-image mb-3 rounded-circle mx-auto" src="~/assets/images/Hafez.jpg" alt="image">

					<div class="bio mb-3">سلام، حافظ چراغی هستم. به وبسایت شخصی من خوش
						آمدید.</div>
					<ul class="social-list list-inline py-2 mx-auto">
						<li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a>
						</li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
					</ul>
					<hr>
				</div>
				<ul class="navbar-nav flex-column text-right">
					<li class="nav-item">
						<a class="nav-link" asp-controller="Home" asp-action="Index"><i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Home" asp-action="Contact"><i
							                                                               class="fas fa-envelope-open-text fa-fw ml-2"></i>ارتباط با من</a>
					</li>
				</ul>
			</div></nav></div>
</header>

DevCard_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
	<title>@ViewData["Title"]</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="favicon.ico">

	<script defer src="~/assets/fontawesome/js/all.js"></script>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css" />
	<link rel="stylesheet" href="~/assets/css/theme-1.css">
	<link rel="stylesheet" href="~/assets/css/style.css">

</head>

<body>

	<partial name="Header" />

	<div class="main-wrapper">

		@RenderBody()

		<partial name="Footer" />

	</div>


	<!-- Javascript -->
	<script src="~/assets/plugins/jquery-3.4.1.min.js"></script>
	<script src="~/assets/plugins/popper.min.js"></script>
<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>

@* validation jquery scripts (unobtrusive) *@

@*<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>*@

@*<script type="text/javascript" src="@Url.Action("Index","Test")"></script>*@
</body>

</html>